# -*- coding: utf-8 -*-
"""Quik_Sort_ADAipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfecXNFQhINTlsIubXaS6i8zNCu7qoFt
"""

import random

def quik_sort(a):
    n = len(a)

    if n <= 1:
        return a

    # _# choose pivot_
    r = random.randint(0, n - 1)
    a[0], a[r] = a[r], a[0]

    # _# 2-way partition_
    k = 0


    for i in range(1, n):
        if a[i] < a[0]:
            k += 1
            a[k], a[i] = a[i], a[k]

    # swap a[1,k]
    a[0], a[k] = a[k], a[0]



    # _# recursive sorts_

    l= sort(a[0:k])


    ri = sort(a[k+1:n])

    return l + [a[k]] + ri